name: Build and Test Fyne App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Fyne App
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install system dependencies for Fyne
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libxi-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb1-dev \
            libx11-xcb1 \
            libxrender-dev \
            libxext-dev \
            xorg-dev

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1  # Specify your desired Go version

      # Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install Fyne CLI
      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the application using Fyne CLI
      - name: Build the app with Fyne
        run: fyne build .
