name: Build and Test Fyne App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    name: Build, Test, and Create Beta Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install system dependencies for Fyne
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libxi-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libx11-dev \
            libxcb1-dev \
            libxrender-dev \
            libxext-dev \
            xorg-dev

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1  # Specify your desired Go version

      # Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install Fyne CLI
      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the application using Fyne CLI
      - name: Build the app with Fyne
        run: fyne build -o ./build/studentNameLearner.exe

      # Archive the built artifact
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: fyne-app
          path: ./build/myapp

      # Create a GitHub Release and upload the binary
      - name: Create Beta Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/myapp
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: beta-1.0.0
          name: Beta Release 1.0.0
          body: "This is a beta release of the studentNameLearner app."
          draft: false
          prerelease: true
