name: Build and Test Fyne App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Fyne App
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1  # Specify your desired Go version

      # Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the application
      - name: Build the app
        run: go build -o ./build/app .

      # Check for Fyne-specific requirements
      - name: Check Fyne Dependencies
        run: |
          if ! command -v x11 &> /dev/null && ! command -v wayland &> /dev/null; then
            echo "WARNING: Fyne may require GUI-related dependencies (X11/Wayland) to run on this environment."
          fi

      # Optionally: Archive the build artifact (binary)
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: fyne-app
          path: ./build/app
